### ISSUE TITLE
Combine with consistent search

### ISSUE THREAD

**Issue by sQVe** [rktjmp/highlight-current-n.nvim#1]
👋🏼 

This plugin is awesome and solves a long standing gripe I've had with vim. I'm wondering how I can combine it with the following:

```viml
" Consistent centered search with n and N.
noremap <expr> n 'Nn'[v:searchforward] . 'zzzv'
noremap <expr> N 'nN'[v:searchforward] . 'zzzv'
```

The above binding essentially makes `n` and `N` always move in a consistent direction and also centers the current match. Would it be possible to get this to work together with this plugin? 🤔

**Comment by rktjmp** [comment]
I wonder if you can sub 'Nn' with `<Plug>..N<plug>n`?

**Comment by rktjmp** [comment]
Also note in the demo config I use `map` not `noremap` for * -> *N, so try that too? I will have a poke myself when I have time but those are where I would start.

**Comment by sQVe** [comment]
I played around with this earlier and couldn't really get it to play nicely. Will probably have to create a function instead or something.

**Comment by megalithic** [comment]
Any luck on this @sQVe / @rktjmp ??

**Comment by rktjmp** [comment]
I *think* this does what you want?

/return ->n n n n -> increasing line numbers
/return -> N N N -> decreasing line numbers
?return -> n n n -> increasing
?return -> N N -> decreasing

It's transpiled from fennel so the variable names are a bit odd, but it should be clear enough to write as you like:

```lua
local function _1_()
  local hcn = require("highlight_current_n")
  local feedkeys = vim.api.nvim_feedkeys
  local _2_ = vim.v.searchforward
  if (_2_ == 0) then
    hcn.N()
    return feedkeys("zzzv", "n", false)
  elseif (_2_ == 1) then
    hcn.n()
    return feedkeys("zzzv", "n", false)
  else
    return nil
  end
end
vim.keymap.set("n", "n", _1_, {noremap = true})

local function _4_()
  local hcn = require("highlight_current_n")
  local feedkeys = vim.api.nvim_feedkeys
  local _5_ = vim.v.searchforward
  if (_5_ == 0) then
    hcn.n()
    return feedkeys("zzzv", "n", false)
  elseif (_5_ == 1) then
    hcn.N()
    return feedkeys("zzzv", "n", false)
  else
    return nil
  end
end
vim.keymap.set("n", "N", _4_, {noremap = true})
```

(edit: not sure how to do it with just viml.)
